### ISSUE TITLE
Dockerfile : Not able to build the Docker

### ISSUE THREAD

**Issue by Jefkeh** [Anchor-Protocol/anchor-web-app#288]
Unable to utilize #249 seems to be failing on the compile. Any instructions on building the docker? @mandrean 

command I'm running sudo docker build -t anchorweb .

error:
 => ERROR [build-local 7/7] RUN yarn run landing:build                                                                                                                                                                                  3.9s
------
 > [build-local 7/7] RUN yarn run landing:build:
#15 3.734 The following changes are being made to your tsconfig.json file:
#15 3.735   - compilerOptions.paths must not be set (aliased imports are not supported)
#15 3.735
#15 3.815 /src/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:124
#15 3.815             throw new Error('When you use this plugin you must install `typescript`.');
#15 3.815             ^
#15 3.815
#15 3.815 Error: When you use this plugin you must install `typescript`.
#15 3.815     at ForkTsCheckerWebpackPlugin.validateTypeScript (/src/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:124:19)
#15 3.815     at new ForkTsCheckerWebpackPlugin (/src/node_modules/fork-ts-checker-webpack-plugin/lib/index.js:80:23)
#15 3.815     at expandPluginsTsChecker (/src/node_modules/react-app-rewire-alias/src/aliasDangerous.js:105:26)
#15 3.815     at /src/node_modules/react-app-rewire-alias/src/aliasDangerous.js:132:5
#15 3.815     at Object.webpack (/src/landing/config-overrides.js:32:7)
#15 3.815     at /src/node_modules/react-app-rewired/overrides/webpack.js:18:23
#15 3.815     at Object.<anonymous> (/src/node_modules/react-scripts/scripts/build.js:67:16)
#15 3.815     at Module._compile (node:internal/modules/cjs/loader:1103:14)
#15 3.815     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
#15 3.815     at Module.load (node:internal/modules/cjs/loader:981:32)
------
executor failed running [/bin/sh -c yarn run landing:build]: exit code: 1

**Comment by mandrean** [comment]
@Jefkeh Yeah you're right, found some quirk when running a local Dockerized build:
https://github.com/Anchor-Protocol/anchor-web-app/blob/master/Dockerfile#L1-L11

The CI uses a different way: https://github.com/Anchor-Protocol/anchor-web-app/blob/master/Dockerfile#L13-L18

Fixed in #290.
