### ISSUE TITLE
anchor gov page got the blank

### ISSUE THREAD

**Issue by mauver** [Anchor-Protocol/anchor-web-app#336]
white page is shown. maybe some bug

react-dom.production.min.js:216 Error: [big.js] Invalid number
    at parse$5 (big.mjs:139:11)
    at new tt (big.mjs:106:7)
    at tt (big.mjs:89:65)
    at formatRate (unit.format.ts:96:23)
    at index.tsx:84:17
    at Object.ci [as useMemo] (react-dom.production.min.js:168:377)
    at Object.react_production_min$1.useMemo (react.production.min.js:23:113)
    at OverviewBase (index.tsx:80:30)
    at Ch$1 (react-dom.production.min.js:157:137)
    at li (react-dom.production.min.js:180:154)

and got this error on console.

big.mjs:139 Uncaught Error: [big.js] Invalid number
    at parse$5 (big.mjs:139:11)
    at new tt (big.mjs:106:7)
    at tt (big.mjs:89:65)
    at formatRate (unit.format.ts:96:23)
    at index.tsx:84:17
    at Object.ci [as useMemo] (react-dom.production.min.js:168:377)
    at Object.react_production_min$1.useMemo (react.production.min.js:23:113)
    at OverviewBase (index.tsx:80:30)
    at Ch$1 (react-dom.production.min.js:157:137)
    at li (react-dom.production.min.js:180:154)

looks like big number error

**Comment by RICARDO4355** [comment]
hi @mauver i just went through this, a bug seems to be promting this error. I will suggest you contact Terra support and talk with a Developer from Terra through their live chat Developers forum. Click on the  Forum ——>> [TERRA SUPPORT LIVE CHAT](https://agora.terras.live/) to help you sort this out right away

**Comment by mauver** [comment]
> 

this link is scam maybe. don't click this link.
